// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package server

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for ClusterSpecServiceType.
const (
	ClusterSpecServiceTypeCluster ClusterSpecServiceType = "cluster"
)

// Valid indicates whether the value is a known member of the ClusterSpecServiceType enum.
func (e ClusterSpecServiceType) Valid() bool {
	switch e {
	case ClusterSpecServiceTypeCluster:
		return true
	default:
		return false
	}
}

// Defines values for ControlPlaneNodesCount.
const (
	N1 ControlPlaneNodesCount = 1
	N3 ControlPlaneNodesCount = 3
	N5 ControlPlaneNodesCount = 5
)

// Valid indicates whether the value is a known member of the ControlPlaneNodesCount enum.
func (e ControlPlaneNodesCount) Valid() bool {
	switch e {
	case N1:
		return true
	case N3:
		return true
	case N5:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Healthy   HealthStatus = "healthy"
	Unhealthy HealthStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Healthy:
		return true
	case Unhealthy:
		return true
	default:
		return false
	}
}

// Defines values for VMSpecServiceType.
const (
	Vm VMSpecServiceType = "vm"
)

// Valid indicates whether the value is a known member of the VMSpecServiceType enum.
func (e VMSpecServiceType) Valid() bool {
	switch e {
	case Vm:
		return true
	default:
		return false
	}
}

// Access defines model for Access.
type Access struct {
	SshPublicKey *string `json:"ssh_public_key,omitempty"`
}

// Cluster Kubernetes cluster resource
type Cluster struct {
	// ApiEndpoint Kubernetes API endpoint URL (populated when ACTIVE)
	ApiEndpoint *string `json:"api_endpoint,omitempty"`
	Id          *string `json:"id,omitempty"`

	// Kubeconfig Base64-encoded kubeconfig for cluster access (populated when ACTIVE)
	Kubeconfig *string `json:"kubeconfig,omitempty"`

	// Path Resource path (e.g. clusters/{id})
	Path *string `json:"path,omitempty"`

	// Spec Provider-agnostic cluster specification aligned with the DCM catalog ClusterSpec
	Spec   ClusterSpec `json:"spec"`
	Status *string     `json:"status,omitempty"`
}

// ClusterList defines model for ClusterList.
type ClusterList struct {
	NextPageToken *string    `json:"next_page_token,omitempty"`
	Results       *[]Cluster `json:"results,omitempty"`
}

// ClusterSpec Provider-agnostic cluster specification aligned with the DCM catalog ClusterSpec
type ClusterSpec struct {
	Metadata *ServiceMetadata `json:"metadata,omitempty"`
	Nodes    *Nodes           `json:"nodes,omitempty"`

	// ProviderHints Provider-specific configuration (e.g. kcli profile overrides)
	ProviderHints *ProviderHints         `json:"provider_hints,omitempty"`
	ServiceType   ClusterSpecServiceType `json:"service_type"`

	// Version Kubernetes version (e.g. 1.30)
	Version              *string                `json:"version,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ClusterSpecServiceType defines model for ClusterSpec.ServiceType.
type ClusterSpecServiceType string

// ControlPlaneNodes defines model for ControlPlaneNodes.
type ControlPlaneNodes struct {
	Count *ControlPlaneNodesCount `json:"count,omitempty"`
}

// ControlPlaneNodesCount defines model for ControlPlaneNodes.Count.
type ControlPlaneNodesCount int

// Disk defines model for Disk.
type Disk struct {
	// Capacity Disk capacity with unit suffix (MB, GB, TB)
	Capacity string `json:"capacity"`
	Name     string `json:"name"`
}

// Error RFC 7807 compliant error response
type Error struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// GuestOS defines model for GuestOS.
type GuestOS struct {
	// Type OS identifier mapped to a kcli profile (e.g. fedora-39, rhel-9)
	Type string `json:"type"`
}

// Health defines model for Health.
type Health struct {
	Message *string       `json:"message,omitempty"`
	Status  *HealthStatus `json:"status,omitempty"`
	Uptime  *float32      `json:"uptime,omitempty"`
	Version *string       `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Memory defines model for Memory.
type Memory struct {
	// Size Memory size with unit suffix (MB, GB, TB)
	Size string `json:"size"`
}

// Nodes defines model for Nodes.
type Nodes struct {
	ControlPlane *ControlPlaneNodes `json:"control_plane,omitempty"`
	Workers      *WorkerNodes       `json:"workers,omitempty"`
}

// ProviderHints Provider-specific configuration (e.g. kcli profile overrides)
type ProviderHints map[string]interface{}

// ServiceMetadata defines model for ServiceMetadata.
type ServiceMetadata struct {
	Labels *map[string]string `json:"labels,omitempty"`
	Name   string             `json:"name"`
}

// Storage defines model for Storage.
type Storage struct {
	Disks *[]Disk `json:"disks,omitempty"`
}

// VM Virtual Machine resource
type VM struct {
	Id *string `json:"id,omitempty"`

	// Ip IP address of the VM (when available from kweb)
	Ip *string `json:"ip,omitempty"`

	// Path Resource path (e.g. vms/{id})
	Path *string `json:"path,omitempty"`

	// Spec Provider-agnostic VM specification aligned with the DCM catalog VMSpec
	Spec VMSpec `json:"spec"`

	// SshUser Default SSH user for the VM (e.g. fedora, core, centos)
	SshUser *string `json:"ssh_user,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// VMList defines model for VMList.
type VMList struct {
	NextPageToken *string `json:"next_page_token,omitempty"`
	Results       *[]VM   `json:"results,omitempty"`
}

// VMSpec Provider-agnostic VM specification aligned with the DCM catalog VMSpec
type VMSpec struct {
	Access   *Access          `json:"access,omitempty"`
	GuestOs  *GuestOS         `json:"guest_os,omitempty"`
	Memory   *Memory          `json:"memory,omitempty"`
	Metadata *ServiceMetadata `json:"metadata,omitempty"`

	// ProviderHints Provider-specific configuration (e.g. kcli profile overrides)
	ProviderHints        *ProviderHints         `json:"provider_hints,omitempty"`
	ServiceType          VMSpecServiceType      `json:"service_type"`
	Storage              *Storage               `json:"storage,omitempty"`
	Vcpu                 *Vcpu                  `json:"vcpu,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// VMSpecServiceType defines model for VMSpec.ServiceType.
type VMSpecServiceType string

// Vcpu defines model for Vcpu.
type Vcpu struct {
	Count *int `json:"count,omitempty"`
}

// WorkerNodes defines model for WorkerNodes.
type WorkerNodes struct {
	Count *int `json:"count,omitempty"`
}

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	MaxPageSize *int    `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
	PageToken   *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateClusterParams defines parameters for CreateCluster.
type CreateClusterParams struct {
	// Id Client-specified instance ID for idempotent creation (provided by SPM)
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// ListVMsParams defines parameters for ListVMs.
type ListVMsParams struct {
	MaxPageSize *int    `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
	PageToken   *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateVMParams defines parameters for CreateVM.
type CreateVMParams struct {
	// Id Client-specified instance ID for idempotent creation (provided by SPM)
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = Cluster

// CreateVMJSONRequestBody defines body for CreateVM for application/json ContentType.
type CreateVMJSONRequestBody = VM

// Getter for additional properties for ClusterSpec. Returns the specified
// element and whether it was found
func (a ClusterSpec) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ClusterSpec
func (a *ClusterSpec) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ClusterSpec to handle AdditionalProperties
func (a *ClusterSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["nodes"]; found {
		err = json.Unmarshal(raw, &a.Nodes)
		if err != nil {
			return fmt.Errorf("error reading 'nodes': %w", err)
		}
		delete(object, "nodes")
	}

	if raw, found := object["provider_hints"]; found {
		err = json.Unmarshal(raw, &a.ProviderHints)
		if err != nil {
			return fmt.Errorf("error reading 'provider_hints': %w", err)
		}
		delete(object, "provider_hints")
	}

	if raw, found := object["service_type"]; found {
		err = json.Unmarshal(raw, &a.ServiceType)
		if err != nil {
			return fmt.Errorf("error reading 'service_type': %w", err)
		}
		delete(object, "service_type")
	}

	if raw, found := object["version"]; found {
		err = json.Unmarshal(raw, &a.Version)
		if err != nil {
			return fmt.Errorf("error reading 'version': %w", err)
		}
		delete(object, "version")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ClusterSpec to handle AdditionalProperties
func (a ClusterSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Metadata != nil {
		object["metadata"], err = json.Marshal(a.Metadata)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
		}
	}

	if a.Nodes != nil {
		object["nodes"], err = json.Marshal(a.Nodes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'nodes': %w", err)
		}
	}

	if a.ProviderHints != nil {
		object["provider_hints"], err = json.Marshal(a.ProviderHints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider_hints': %w", err)
		}
	}

	object["service_type"], err = json.Marshal(a.ServiceType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'service_type': %w", err)
	}

	if a.Version != nil {
		object["version"], err = json.Marshal(a.Version)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'version': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for VMSpec. Returns the specified
// element and whether it was found
func (a VMSpec) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for VMSpec
func (a *VMSpec) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for VMSpec to handle AdditionalProperties
func (a *VMSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access"]; found {
		err = json.Unmarshal(raw, &a.Access)
		if err != nil {
			return fmt.Errorf("error reading 'access': %w", err)
		}
		delete(object, "access")
	}

	if raw, found := object["guest_os"]; found {
		err = json.Unmarshal(raw, &a.GuestOs)
		if err != nil {
			return fmt.Errorf("error reading 'guest_os': %w", err)
		}
		delete(object, "guest_os")
	}

	if raw, found := object["memory"]; found {
		err = json.Unmarshal(raw, &a.Memory)
		if err != nil {
			return fmt.Errorf("error reading 'memory': %w", err)
		}
		delete(object, "memory")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["provider_hints"]; found {
		err = json.Unmarshal(raw, &a.ProviderHints)
		if err != nil {
			return fmt.Errorf("error reading 'provider_hints': %w", err)
		}
		delete(object, "provider_hints")
	}

	if raw, found := object["service_type"]; found {
		err = json.Unmarshal(raw, &a.ServiceType)
		if err != nil {
			return fmt.Errorf("error reading 'service_type': %w", err)
		}
		delete(object, "service_type")
	}

	if raw, found := object["storage"]; found {
		err = json.Unmarshal(raw, &a.Storage)
		if err != nil {
			return fmt.Errorf("error reading 'storage': %w", err)
		}
		delete(object, "storage")
	}

	if raw, found := object["vcpu"]; found {
		err = json.Unmarshal(raw, &a.Vcpu)
		if err != nil {
			return fmt.Errorf("error reading 'vcpu': %w", err)
		}
		delete(object, "vcpu")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for VMSpec to handle AdditionalProperties
func (a VMSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Access != nil {
		object["access"], err = json.Marshal(a.Access)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'access': %w", err)
		}
	}

	if a.GuestOs != nil {
		object["guest_os"], err = json.Marshal(a.GuestOs)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'guest_os': %w", err)
		}
	}

	if a.Memory != nil {
		object["memory"], err = json.Marshal(a.Memory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'memory': %w", err)
		}
	}

	if a.Metadata != nil {
		object["metadata"], err = json.Marshal(a.Metadata)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
		}
	}

	if a.ProviderHints != nil {
		object["provider_hints"], err = json.Marshal(a.ProviderHints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider_hints': %w", err)
		}
	}

	object["service_type"], err = json.Marshal(a.ServiceType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'service_type': %w", err)
	}

	if a.Storage != nil {
		object["storage"], err = json.Marshal(a.Storage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'storage': %w", err)
		}
	}

	if a.Vcpu != nil {
		object["vcpu"], err = json.Marshal(a.Vcpu)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'vcpu': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List clusters
	// (GET /clusters)
	ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams)
	// Create a cluster
	// (POST /clusters)
	CreateCluster(w http.ResponseWriter, r *http.Request, params CreateClusterParams)
	// Cluster service health check
	// (GET /clusters/health)
	GetClusterHealth(w http.ResponseWriter, r *http.Request)
	// Delete a cluster
	// (DELETE /clusters/{clusterId})
	DeleteCluster(w http.ResponseWriter, r *http.Request, clusterId string)
	// Get a cluster
	// (GET /clusters/{clusterId})
	GetCluster(w http.ResponseWriter, r *http.Request, clusterId string)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List VMs
	// (GET /vms)
	ListVMs(w http.ResponseWriter, r *http.Request, params ListVMsParams)
	// Create a VM
	// (POST /vms)
	CreateVM(w http.ResponseWriter, r *http.Request, params CreateVMParams)
	// VM service health check
	// (GET /vms/health)
	GetVMHealth(w http.ResponseWriter, r *http.Request)
	// Delete a VM
	// (DELETE /vms/{vmId})
	DeleteVM(w http.ResponseWriter, r *http.Request, vmId string)
	// Get a VM
	// (GET /vms/{vmId})
	GetVM(w http.ResponseWriter, r *http.Request, vmId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List clusters
// (GET /clusters)
func (_ Unimplemented) ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a cluster
// (POST /clusters)
func (_ Unimplemented) CreateCluster(w http.ResponseWriter, r *http.Request, params CreateClusterParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cluster service health check
// (GET /clusters/health)
func (_ Unimplemented) GetClusterHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a cluster
// (DELETE /clusters/{clusterId})
func (_ Unimplemented) DeleteCluster(w http.ResponseWriter, r *http.Request, clusterId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a cluster
// (GET /clusters/{clusterId})
func (_ Unimplemented) GetCluster(w http.ResponseWriter, r *http.Request, clusterId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List VMs
// (GET /vms)
func (_ Unimplemented) ListVMs(w http.ResponseWriter, r *http.Request, params ListVMsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a VM
// (POST /vms)
func (_ Unimplemented) CreateVM(w http.ResponseWriter, r *http.Request, params CreateVMParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// VM service health check
// (GET /vms/health)
func (_ Unimplemented) GetVMHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a VM
// (DELETE /vms/{vmId})
func (_ Unimplemented) DeleteVM(w http.ResponseWriter, r *http.Request, vmId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a VM
// (GET /vms/{vmId})
func (_ Unimplemented) GetVM(w http.ResponseWriter, r *http.Request, vmId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListClusters operation middleware
func (siw *ServerInterfaceWrapper) ListClusters(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListClustersParams

	// ------------- Optional query parameter "max_page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_page_size", r.URL.Query(), &params.MaxPageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_token", r.URL.Query(), &params.PageToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClusters(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCluster operation middleware
func (siw *ServerInterfaceWrapper) CreateCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateClusterParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "id", r.URL.Query(), &params.Id, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCluster(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetClusterHealth operation middleware
func (siw *ServerInterfaceWrapper) GetClusterHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetClusterHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCluster operation middleware
func (siw *ServerInterfaceWrapper) DeleteCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "clusterId" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "clusterId", chi.URLParam(r, "clusterId"), &clusterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "clusterId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCluster(w, r, clusterId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCluster operation middleware
func (siw *ServerInterfaceWrapper) GetCluster(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "clusterId" -------------
	var clusterId string

	err = runtime.BindStyledParameterWithOptions("simple", "clusterId", chi.URLParam(r, "clusterId"), &clusterId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "clusterId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCluster(w, r, clusterId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVMs operation middleware
func (siw *ServerInterfaceWrapper) ListVMs(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListVMsParams

	// ------------- Optional query parameter "max_page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_page_size", r.URL.Query(), &params.MaxPageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_token", r.URL.Query(), &params.PageToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVMs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateVM operation middleware
func (siw *ServerInterfaceWrapper) CreateVM(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateVMParams

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "id", r.URL.Query(), &params.Id, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVM(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVMHealth operation middleware
func (siw *ServerInterfaceWrapper) GetVMHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVMHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVM operation middleware
func (siw *ServerInterfaceWrapper) DeleteVM(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", chi.URLParam(r, "vmId"), &vmId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vmId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVM(w, r, vmId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVM operation middleware
func (siw *ServerInterfaceWrapper) GetVM(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vmId" -------------
	var vmId string

	err = runtime.BindStyledParameterWithOptions("simple", "vmId", chi.URLParam(r, "vmId"), &vmId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vmId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVM(w, r, vmId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/clusters", wrapper.ListClusters)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/clusters", wrapper.CreateCluster)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/clusters/health", wrapper.GetClusterHealth)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/clusters/{clusterId}", wrapper.DeleteCluster)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/clusters/{clusterId}", wrapper.GetCluster)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vms", wrapper.ListVMs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/vms", wrapper.CreateVM)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vms/health", wrapper.GetVMHealth)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/vms/{vmId}", wrapper.DeleteVM)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vms/{vmId}", wrapper.GetVM)
	})

	return r
}

type ListClustersRequestObject struct {
	Params ListClustersParams
}

type ListClustersResponseObject interface {
	VisitListClustersResponse(w http.ResponseWriter) error
}

type ListClusters200JSONResponse ClusterList

func (response ListClusters200JSONResponse) VisitListClustersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListClustersdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListClustersdefaultApplicationProblemPlusJSONResponse) VisitListClustersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateClusterRequestObject struct {
	Params CreateClusterParams
	Body   *CreateClusterJSONRequestBody
}

type CreateClusterResponseObject interface {
	VisitCreateClusterResponse(w http.ResponseWriter) error
}

type CreateCluster201JSONResponse Cluster

func (response CreateCluster201JSONResponse) VisitCreateClusterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCluster400ApplicationProblemPlusJSONResponse Error

func (response CreateCluster400ApplicationProblemPlusJSONResponse) VisitCreateClusterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCluster409ApplicationProblemPlusJSONResponse Error

func (response CreateCluster409ApplicationProblemPlusJSONResponse) VisitCreateClusterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateClusterdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateClusterdefaultApplicationProblemPlusJSONResponse) VisitCreateClusterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetClusterHealthRequestObject struct {
}

type GetClusterHealthResponseObject interface {
	VisitGetClusterHealthResponse(w http.ResponseWriter) error
}

type GetClusterHealth200JSONResponse Health

func (response GetClusterHealth200JSONResponse) VisitGetClusterHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetClusterHealth503JSONResponse Health

func (response GetClusterHealth503JSONResponse) VisitGetClusterHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteClusterRequestObject struct {
	ClusterId string `json:"clusterId"`
}

type DeleteClusterResponseObject interface {
	VisitDeleteClusterResponse(w http.ResponseWriter) error
}

type DeleteCluster204Response struct {
}

func (response DeleteCluster204Response) VisitDeleteClusterResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCluster404ApplicationProblemPlusJSONResponse Error

func (response DeleteCluster404ApplicationProblemPlusJSONResponse) VisitDeleteClusterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteClusterdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteClusterdefaultApplicationProblemPlusJSONResponse) VisitDeleteClusterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetClusterRequestObject struct {
	ClusterId string `json:"clusterId"`
}

type GetClusterResponseObject interface {
	VisitGetClusterResponse(w http.ResponseWriter) error
}

type GetCluster200JSONResponse Cluster

func (response GetCluster200JSONResponse) VisitGetClusterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCluster404ApplicationProblemPlusJSONResponse Error

func (response GetCluster404ApplicationProblemPlusJSONResponse) VisitGetClusterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetClusterdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetClusterdefaultApplicationProblemPlusJSONResponse) VisitGetClusterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse Health

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListVMsRequestObject struct {
	Params ListVMsParams
}

type ListVMsResponseObject interface {
	VisitListVMsResponse(w http.ResponseWriter) error
}

type ListVMs200JSONResponse VMList

func (response ListVMs200JSONResponse) VisitListVMsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListVMsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListVMsdefaultApplicationProblemPlusJSONResponse) VisitListVMsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVMRequestObject struct {
	Params CreateVMParams
	Body   *CreateVMJSONRequestBody
}

type CreateVMResponseObject interface {
	VisitCreateVMResponse(w http.ResponseWriter) error
}

type CreateVM201JSONResponse VM

func (response CreateVM201JSONResponse) VisitCreateVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVM400ApplicationProblemPlusJSONResponse Error

func (response CreateVM400ApplicationProblemPlusJSONResponse) VisitCreateVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVM409ApplicationProblemPlusJSONResponse Error

func (response CreateVM409ApplicationProblemPlusJSONResponse) VisitCreateVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateVMdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateVMdefaultApplicationProblemPlusJSONResponse) VisitCreateVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetVMHealthRequestObject struct {
}

type GetVMHealthResponseObject interface {
	VisitGetVMHealthResponse(w http.ResponseWriter) error
}

type GetVMHealth200JSONResponse Health

func (response GetVMHealth200JSONResponse) VisitGetVMHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVMHealth503JSONResponse Health

func (response GetVMHealth503JSONResponse) VisitGetVMHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteVMRequestObject struct {
	VmId string `json:"vmId"`
}

type DeleteVMResponseObject interface {
	VisitDeleteVMResponse(w http.ResponseWriter) error
}

type DeleteVM204Response struct {
}

func (response DeleteVM204Response) VisitDeleteVMResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteVM404ApplicationProblemPlusJSONResponse Error

func (response DeleteVM404ApplicationProblemPlusJSONResponse) VisitDeleteVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteVMdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteVMdefaultApplicationProblemPlusJSONResponse) VisitDeleteVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetVMRequestObject struct {
	VmId string `json:"vmId"`
}

type GetVMResponseObject interface {
	VisitGetVMResponse(w http.ResponseWriter) error
}

type GetVM200JSONResponse VM

func (response GetVM200JSONResponse) VisitGetVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVM404ApplicationProblemPlusJSONResponse Error

func (response GetVM404ApplicationProblemPlusJSONResponse) VisitGetVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVMdefaultApplicationProblemPlusJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetVMdefaultApplicationProblemPlusJSONResponse) VisitGetVMResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List clusters
	// (GET /clusters)
	ListClusters(ctx context.Context, request ListClustersRequestObject) (ListClustersResponseObject, error)
	// Create a cluster
	// (POST /clusters)
	CreateCluster(ctx context.Context, request CreateClusterRequestObject) (CreateClusterResponseObject, error)
	// Cluster service health check
	// (GET /clusters/health)
	GetClusterHealth(ctx context.Context, request GetClusterHealthRequestObject) (GetClusterHealthResponseObject, error)
	// Delete a cluster
	// (DELETE /clusters/{clusterId})
	DeleteCluster(ctx context.Context, request DeleteClusterRequestObject) (DeleteClusterResponseObject, error)
	// Get a cluster
	// (GET /clusters/{clusterId})
	GetCluster(ctx context.Context, request GetClusterRequestObject) (GetClusterResponseObject, error)
	// Health check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// List VMs
	// (GET /vms)
	ListVMs(ctx context.Context, request ListVMsRequestObject) (ListVMsResponseObject, error)
	// Create a VM
	// (POST /vms)
	CreateVM(ctx context.Context, request CreateVMRequestObject) (CreateVMResponseObject, error)
	// VM service health check
	// (GET /vms/health)
	GetVMHealth(ctx context.Context, request GetVMHealthRequestObject) (GetVMHealthResponseObject, error)
	// Delete a VM
	// (DELETE /vms/{vmId})
	DeleteVM(ctx context.Context, request DeleteVMRequestObject) (DeleteVMResponseObject, error)
	// Get a VM
	// (GET /vms/{vmId})
	GetVM(ctx context.Context, request GetVMRequestObject) (GetVMResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListClusters operation middleware
func (sh *strictHandler) ListClusters(w http.ResponseWriter, r *http.Request, params ListClustersParams) {
	var request ListClustersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListClusters(ctx, request.(ListClustersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListClusters")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListClustersResponseObject); ok {
		if err := validResponse.VisitListClustersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCluster operation middleware
func (sh *strictHandler) CreateCluster(w http.ResponseWriter, r *http.Request, params CreateClusterParams) {
	var request CreateClusterRequestObject

	request.Params = params

	var body CreateClusterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCluster(ctx, request.(CreateClusterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCluster")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateClusterResponseObject); ok {
		if err := validResponse.VisitCreateClusterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetClusterHealth operation middleware
func (sh *strictHandler) GetClusterHealth(w http.ResponseWriter, r *http.Request) {
	var request GetClusterHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetClusterHealth(ctx, request.(GetClusterHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetClusterHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetClusterHealthResponseObject); ok {
		if err := validResponse.VisitGetClusterHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCluster operation middleware
func (sh *strictHandler) DeleteCluster(w http.ResponseWriter, r *http.Request, clusterId string) {
	var request DeleteClusterRequestObject

	request.ClusterId = clusterId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCluster(ctx, request.(DeleteClusterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCluster")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteClusterResponseObject); ok {
		if err := validResponse.VisitDeleteClusterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCluster operation middleware
func (sh *strictHandler) GetCluster(w http.ResponseWriter, r *http.Request, clusterId string) {
	var request GetClusterRequestObject

	request.ClusterId = clusterId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCluster(ctx, request.(GetClusterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCluster")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetClusterResponseObject); ok {
		if err := validResponse.VisitGetClusterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVMs operation middleware
func (sh *strictHandler) ListVMs(w http.ResponseWriter, r *http.Request, params ListVMsParams) {
	var request ListVMsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVMs(ctx, request.(ListVMsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVMs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVMsResponseObject); ok {
		if err := validResponse.VisitListVMsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateVM operation middleware
func (sh *strictHandler) CreateVM(w http.ResponseWriter, r *http.Request, params CreateVMParams) {
	var request CreateVMRequestObject

	request.Params = params

	var body CreateVMJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateVM(ctx, request.(CreateVMRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateVM")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateVMResponseObject); ok {
		if err := validResponse.VisitCreateVMResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVMHealth operation middleware
func (sh *strictHandler) GetVMHealth(w http.ResponseWriter, r *http.Request) {
	var request GetVMHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVMHealth(ctx, request.(GetVMHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVMHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVMHealthResponseObject); ok {
		if err := validResponse.VisitGetVMHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteVM operation middleware
func (sh *strictHandler) DeleteVM(w http.ResponseWriter, r *http.Request, vmId string) {
	var request DeleteVMRequestObject

	request.VmId = vmId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteVM(ctx, request.(DeleteVMRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteVM")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteVMResponseObject); ok {
		if err := validResponse.VisitDeleteVMResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVM operation middleware
func (sh *strictHandler) GetVM(w http.ResponseWriter, r *http.Request, vmId string) {
	var request GetVMRequestObject

	request.VmId = vmId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVM(ctx, request.(GetVMRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVM")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVMResponseObject); ok {
		if err := validResponse.VisitGetVMResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
