// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXPbuBH+Kxg0H5Ie9eI46TX60omd1PE0TDynq/oh43pgcinhDAIMAMrR+fTfO3iT",
	"KAp68Y2tur18ySjSAgs8++yzu6TvcCbKSnDgWuHBHVbZBEpiP77NMlD2UyVFBVJTcCZqclXV14xmVzcw",
	"M9/oWQV4gJWWlI/xfJ6Eb8T1L5BpPE/wKauVBmmsc1CZpJWmguMB/kd9DZKDBoUyZ4MkKFHLDHDS8kxz",
	"868Ekn/mbIYHWtaQtL0nuCJ6su7oJ78rMj+j59Add4NH1buj+fwFTnbvrSrIzN7PJBR4gP/UW8LX89j1",
	"/F2HxtQs0UTXao+Tz43/rzWVkOPBF+fqcjOWH6nS69Hh8E1fVWQMV1rcAI+Ex3hRNXPxphpKteeF8DKw",
	"REoy2xrpoQeK5Dk1ESDsonFOd//VAF1IMaU5yA4Zc6E0zRaEMEjQgmbEWCLC6JhDjm6pniA9AfTuNEUZ",
	"0YSJMWp6b9OnBE1yosmu6w5BTmkGaTCfJ5iLHHbC9Mkaza1be5OrCfVptW1ZuPcHa2wI4/xfOWjvMPC6",
	"NITwcDQ4sQzpFKSyMG7JL2/juX/UPe4byu8gYfMsUTIKrqVgF4xw+BRQWsU9EzXXjYscJcfJ6+VelGsY",
	"G3bF2PSOqpvIjqQiGdWz9esaexR+dhSpOdVI1UVBv6Hn6UmCzk4S9POJuXtFtAZp1v37S7/z5vKH5+nJ",
	"b2cnv/188uIZjqDMSWkj0lxHOr+apc/9h87ln8NXL/72bCe+dsdkeaEYxO+lFBHl/Onvp+jHv/Z/RIZT",
	"jBKuERhLo5+V4GpdP3PQhLKoJFCuNOGZvV0hZEk0HuBa0o6EAiRwq8brariQtnYsE6ypZhD1FXi9r58W",
	"ZPbXsH8Mr7MalP48XKdNcLyK4+chojlwTQsKEpWkqiBHWiCCbjJGUSVFQRn4rCkgF5J0jt8kSE6Add68",
	"2O+8sXN+AMJcpWrrlFJkHMduiXhQhYoohRNcmMjGlKGuNC1X8S6YIHp5bl6X1y5mDRXZo6anUAo5izQI",
	"9NcIzM4amR8fOC/bkmXcx/DeKE9Wwa4qI2E7S+Ga3M0TfCvkDcidQv8va+ZXxQBdrQS/r3iGWokywQs6",
	"rqUrmo69K4QWU5CS5qAaFF6epV0E12Bj5BrYllNuTPyGk6CnJfn2EfjYJMNfjhNcUh7+e5TExbbjP91f",
	"bGPMGGohfca1FJOqm/37JFus9mqSRul6goyo1DVhKCXZhHI4YBs8LR+4Ax6lj9b8jtLD9b2jdN9oPkS3",
	"O0rv0+h6n21ukMXQtu1ifrSbJ3hsauWV2Lki1NR5gsuF7G9b4IuDtf/dbfcjNdLTMlop1VIFtp7Tm5l6",
	"mVX1ThIZm3u31SO/84ZOuqScluYyR/u10c3S81C7zm3bWIhIE36aulLjQ4pCZFAhpOE54fliuGO0gGyW",
	"MUAl4WQMJXCNppSgm1u4xglmNAPTzJoct+UCv61INgH0stvHCa4lwwM80bpSg17v9va2S+zPXSHHPb9W",
	"9T6en77/NHzfedntdye6ZI0GFcdP+vbiHDcaIjw9IqyakCOzUlTASUXxAB93+91XrmGZWCx74ZGC+c8Y",
	"LKwGa5vR5zkeYCNfp8HIrJSkBLfiyx2mxtfXGuQMh/JoqqNTNtvZJP4ZjYO9IDXTePC6nxgzH71+P9kR",
	"y7ijhnw2vbSV+tIqqR0x7DVf9vuhjwJHJFJVzKtY7xflGsrlfns8arAabxm2yqxhbZWrqBlaoIqtlQdi",
	"4zEqKa4ZlD/c7zhu9Ioc5J8cvlWQacjd0GUTRNVlSYw02iAvni6ZvoSM1coIb8RNqAg9TiUQDeGJyxo/",
	"Vk9xyihwHXo+yFEY49D5O5trNIeyEgYPlJmNbSvoVTVH1zM0vEhN1Y+xgea7WfDVlIUTkc8emgAO86Vk",
	"mhI6X+Pd0eO4bYPshGoBoNJEasgN715tpf4Dc+6cTwmjJshVrZ8i6x13EQnMjxJ/nixFsjdZjMBeK1f9",
	"uQkZZRPIbhDwvBKUa1SrBXctyU1rFKpJ6Bhw0sqrMwiq68fuRxQx7yGmX77MUIXc1W2H9Lp/fFjfNV94",
	"Xw1geODqTScN/BvB9FFrxfLOfzrP5y6SDDSsC9w7+/1GgbNKZEeXhRAt9sVtRbhflXq1TrBwYXdYn9Kv",
	"DpdQwT8XGhWi5vlTTGsXsR1pncS7nWXaHTTU/UMUhk3NyHcGtRl0BnqPqrBWDNao9F26N0r3hz2kelpu",
	"H0tG6feJJPIQ6P9iGHGxDbSYljtHkFH6B5w+RumhB4/gsfUsOHWIPYUp41X/zQHLmeAFo9nTHm9saqyk",
	"klfXh5tnRunWUWaUfi+FG0vhKL3XAGPffkzLvcaWmChG2liz28MPK6P0vzanjNL/kRFlPTU3DyaHC2b/",
	"kcvFk5hEnjpH3BAS0W7/pihQwL1R6JGK9pYP/S8Xi/Z9bdt4ndHkEjat7t5/AhndJFv8Od7W+rJgglou",
	"9cI3v5z/JwAA//8YJteu+SkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
