// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXPbuBH+Kxj0Pjg96sWxc9foS8cvqeNp6HiiizrTjKuByaWEMwnwAFCOzqf/3sEL",
	"KUqEJDp1VLfjb7S4wAK7D559FvQDjniWcwZMSTx4wDKaQkbM40kUgTRPueA5CEXBmsjpOC9uUxqN72Cu",
	"f1HzHPAASyUom+DFIih/4be/QqTwIsBnaSEVCG0dg4wEzRXlDA/w34tbEAwUSBRZGyRA8kJEgIM1zySn",
	"Y2BxzilTW2c6ub5EpSH6/OkDOsh5XqREQYzup8DQp89XV5dXF69wgAWQ+CNL53igRAHB+mYCTGPta6fZ",
	"XXELEWcJnTSXdkok/HTcARbxGGK0NEUJF9W+iQn4f7TWnKhp0/0nF1CkX6MD6E66pVPZe6DxotXcModI",
	"z/2DgAQP8J96S+T0HGx6Ls1DbaqHKKIK2SJ8C+3/t4IKiPHgi3V1sxlGH6hUTWAy+KrGOZnAWPE7YB5k",
	"ai+ySC3UqYJMttwQXmKaCEHmW0E+dIEicUx1Bkh6XVun3f9qgq4Fn9EYRIdMGJeKRhUmdCRoQiOiLRFJ",
	"6YRpXFA1RWoK6PwsRBFRJOUTVPe+fnIyUCQmiuza7hDEjEYQluaLADMew84wXRmjhXFrdjKeUsco24aV",
	"+35vjDVgrP+xDe0DBlZkGhAuHDVMLFM6AyFNGLcQgrNx2D/sHvU15HeAsL4WLxg5U4Kn1ylhcFVGaTXu",
	"ES8sVbmNHAZHwZvlXJQpmGh0+dB0TuWdZ0aSk4iqeXO72h6Vry1ECkYVkkWS0K/oIDwN0MVpgH451XvP",
	"iVIg9Lh/fel33t78eBCe/nFx+scvp69+wJ4oM5KZjNTHkc7veuiBe+jc/Ln86dVff9gZXzNjsNyQL8Tv",
	"hOCeovHpb2fo57/0f0YaUyklTCHQlrp05JzJZumIQRGaeimBMqkIi8zuEi4yovAAF4J2BCQggJlC1GTD",
	"itrWcxlgRVUKXl8lrtv6WQuZeVvO74vXRQFSfRw2YVM6Xo3jxyGiMTBFEwoCZSTPIUaKI4LuopSiXPCE",
	"puBOTQIxF6Rz9DZAYgpp5+2rduv1rfM9kNRWqnWekpJM/LFbRrxkhZxIiQOc6Mz6mKHIFc1W452knKjl",
	"ulmR3dqc1VikhZwJIeNi7tFG9HdPmK010i+f+FyuU5Z274v3RnoyDDbONYXtLIUNulsE+J6LOxA7if4f",
	"xsyN8gV0tRJ8W/EsayWy2qoQtmha9K4Ams9ACBqDrEF4uZb1ItgIW0puId2yyo0Hv+ak5NOMfP0AbKIP",
	"w09HAc4oK/88DPxk23FPjydbHzKGigt34tYYk8q79jrJFKtWImkUNg/IiApVkBSFJJpSBps7gJZanOZN",
	"H5fXiMSx0AqbJ0Y8jcI9ae1Z9sQyexRWCltOx4X0NVbnkJAiVWg4fI+0hWk1ym3XCD1AERcQoAiY4rLd",
	"Ep9a1o/C/Sn6UdgWp0+h40fhYyS889noe6tOfNvGXL++CPBEq4Ax3zmiVAuLAGdVQds2wJU9Y//NDcV3",
	"ahFmmVcDyCW/bV2nM9NKIMqLnSDSNo9uGEZu5g09QkYZzfRmDts1CPWi+lSzLowgTriHT85CW0RdSlGZ",
	"GUMsoxARFldta0oTiOZRCigjjEwgA6bQjBJ0dw+3OMApjUDLdH3GTSHEJzmJpoBed/s4wIVI8QBPlcrl",
	"oNe7v7/vEvO6y8Wk58bK3ofLs3dXw3ed191+d6qytCa9sX+lJ9eXuCb18OyQpPmUHOqRPAdGcooH+Kjb",
	"7x5bKTY1seyVlyX6jwmYsOpYmxN9GeMB1vR1VhrpkYJkYEd8ecBU+/qtADHHZeHXdd8ym9Fsgbt4s2E3",
	"xI0Hb/qBNnPZ6/eDHbn0O6rRZ93LOlPfGCY1zZPZ5ut+v1SIYIFE8jx1LNb7VVqpvJyvxSWK4XiDsFVk",
	"DQvDXEmRoiqq2Fi5QGxcRi74bQrZj49bjm0qPQv5zOBrDpFWA+BsAiyLLCOaGk2Sq3szrbjIRK5cTmhy",
	"49IDjzMBREF5l9TAx+oqzlIKTJVqFmJUNqjo8tycNRpDlnMdDxTpiY3Idawao9s5Gl6Huo770EDjFRTU",
	"1OfrN0cNwXnS+WfV4Nvn7th1+e6VX3veWGIEqU55PH9qHNnULZlXV+JFA76H38fteq4s31V5kIoIBbGG",
	"7/HWE/TE0L1kM5JSjZW8UNb72/15P+MsSamtSs/t1Nqzh0h5cr0HdxEsSb43rS4nHNev+rN3FyiaQnS3",
	"/MpQyOrsVUq7rIal4sHBGi9cQFk13IXIdyRh58HHv65MUons1o3Ce9M/2q/vglXeVxNYXoU702kt/rVk",
	"uqyt5fLBPV3GC5vJFBQ0Cfrc/L6RoA2Tmn6vItJqXrxORY+rssdNgJUbtot1XHK8x9Ps/DOuUMILFj/H",
	"Y20ztuNYB361tjx2e011fx8VaZOYekHQOoIuQLWoCo1i0IDSC3VvpO73Lah6lm1vq0bhS0flucT6v2im",
	"bG5LWMyynS3UKHzpnr4dM/tunEqPa5f9oQ38S5f0HLskc8JWTqQj6adri0bh1o5oFL5U1I0VdRQ+qg8y",
	"X55mWavux8etHjWsZ3v6nmcU/tfanVH4P9LpNI/m5v5mf8nsf+dy8SwamueOEdvLeLjbfTArIWA/rPRI",
	"TnvLbx831aC23+VrX3XqWMJaMbf+917vJFH1/5Zb60uFBLkc6ohvcbP4dwAAAP//8mvFzNUsAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
