// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXPbuBH+Kxj0Pjg96sWxc9foS8eWU8fTMPFEOXWmGVcDkUsJZxDgAaBsnU//vYMX",
	"UpRIvThVXLfjb7S4wAK7D559FvQDjkSaCQ5cK9x7wCqaQkrs41kUgbJPmRQZSE3BmajpKMvHjEajW5ib",
	"X/Q8A9zDSkvKJ3ixCIpfxPhXiDReBLjPcqVBGusYVCRppqnguIf/no9BctCgUORskAQlchkBDtY8k4yO",
	"gMeZoFxvnens+goVhuiXzx/QUSaynBENMbqbAkdn/S9Xw3evcIAlkPgTZ3Pc0zKHYH0vAaaxcbXT7DYf",
	"QyR4Qif1lZ0TBT+dtoBHIoYYLU1RImS5bWLj/Z8sNSN6Wvf+2YcTmdfoCNqTduFTdR5ovNhrbpVBZOb+",
	"QUKCe/hPnSVuOh40HZ/kgTE1QzTRudojegvj/7ecSohx76tzdbMZRB+o0nVYcrjXo4xMYKTFLfAGXBov",
	"KmcO6FRDqvbcEF4imkhJ5lshPvCBInFMTQYIu66s0+1/NUHXUsxoDLJFJlwoTaMSEiYSNKERMZaIMDrh",
	"BhZUT5GeArrohygimjAxQVXv6+cmBU1iosmu7Q5AzmgEYWG+CDAXMewM00drtLBu7U5GU+r5ZNuwYt/v",
	"rbEBjPM/cqF9wMDz1ADCh6OCiWVKZyCVDeMWOvA2HvvH7ZOugfwOEFbX0ghGwbUU7JoRDh+LKK3GPRK5",
	"Iyq/kePgJHiznItyDRODriY0XVB12zAjyUhE9by+XWOPitcOIjmnGqk8Seg9OgrPA3R5HqAv52bvGdEa",
	"pBn3r6/d1tubH4/C8z8uz//4cv7qB9wQZU5Sm5HqONL63Qw98g+tmz8XP7366w8742tnDJYbagrxOylF",
	"Q8n4/Lc++vkv3Z+RwRSjhGsExtIUjkxwVS8cMWhCWSMlUK404ZHdXSJkSjTu4VzSloQEJHBbhupsWFLb",
	"ei4DrKlm0OirwPW+ftZCZt8W8zfF6zIHpT8N6rApHK/G8dMA0Ri4pgkFiVKSZRAjLRBBtxGjKJMioQz8",
	"qUkgFpK0Tt4GSE6Btd6+2m+9Tet8D4S5SrXOU0qRSXPslhEvWGFqZ5njAOe8eG5iiDzTNF2Ne8IE0cv1",
	"8zwdu9xV2GQPURNCKuS8QSHR3xvC7ayReXng87lOXcZ9U9w30pRlslFmqGxnSazR3iLAd0LegtxJ+P+w",
	"Zn5UU0BXK8K3FdGiZiInsXLpiqdD8QqwxQykpDGoCpSXa1kvhrWwMTIGtmWVGwmg4qTg1ZTcfwA+MYfi",
	"p5MAp5QXfx4HzaTb8k+PJ90mZAy0kP7krTEnVbf76yVbtPYSS8OwfkCGVOqcMBSSaEo5bO4D9pTkNKv7",
	"uLpGJI6lEdoisSJqGKIjK7TJjFBGxgxQIkWKbu9gfGDVPUsPLLiHYam11XSUq6YG6wISkjONBoP3yFjY",
	"nqPYeIXaAxQJCQGKgGuh9lvioQX+MHw6bT8M90XqIRT9MHyMmPc+a/1v2ZFv25jv2xcBnhg9MBI7RxS6",
	"YRHgtCxp2wb4wmftv7m1+E7NwixtVAFqyXBb1+nNjBaIsnwniIzNo1uHoZ95Q7eQUk5Ts5nj/VqFalk9",
	"1KwLK40T0cAn/dCVUZ9SVGTGEsswRITHZQPLaALRPGKAUsLJBFLgGs0oseyKA8xoBEawmzNuSyE+y0g0",
	"BfS63TXCTjLcw1OtM9XrdO7u7trEvm4LOen4sarz4ar/7uPgXet1u9ue6pRVRDhuXunZ9RWuiD08OyYs",
	"m5JjM1JkwElGcQ+ftLvtUyfGpjaWneLaxPwxARtWE2t7oq9i3MOGvvqFkRkpSQpuxNcHTI2v33KQRrT6",
	"/abk3jGbVW2Bv4BzYbfEjXtvuoEx89nrdoMduWx2VKHPqpd1pr6xTGrbKLvN191uoRHBAYlkGfMs1vlV",
	"ObG8nG+P6xTL8RZhq8ga5Ja5kpyhMqrYWvlAbFxGJsWYQfrj45bj2suGhfzC4T6DSEPsGkt7QFSepsRQ",
	"o01yeYNmNBeZqJVrCkNuQjXAoy+BaChulWr4WF1Fn1HgutCzEKOiVUVXF/as0RjSTJh4oMhMbGWuZ9UY",
	"jedocB2aOt6EBhqvoKCiP1+/OalJzrPWP8tW3z23R77f96+a1eeNI0ZQ+lzE80PjyKVuybymEi9q8D3+",
	"Pm7Xc+X4rsyD0kRqiA18T7eeoAND94rPCKMGK1munfe3T+e9L3jCqKtKz+3UurOHSHFyGw/uIliSfGda",
	"XlN4rl/1524xUDSF6Hb5tSFX5dkrlXZRDQvFg4M1XriEomr4q5HvSMLeQxP/+jJJFSruUxYBftM9eVrf",
	"y9uctQQWl+LedFqJfyWZPmtruXzwT1fxwmWSgYY6QV/Y3zcStGVS2++VRFrOi9ep6HFV9rQOsGLDbrGe",
	"S06f8DR7/1xolIicx8/xWLuM7TjWQbNaWx67J0119ykq0iYx9YKgdQRdgt6jKtSKQQ1KL9S9kbrf70HV",
	"s3R7WzUMXzqqhkus/4tmyuW2gMUs3dlCDcOX7unbMfPUjVPhce26P3SBf+mSnmOXZE/Yyon0JH24tmgY",
	"bu2IhuFLRd1YUYfho/og++Vplu7V/TRxa4MaNrMdvucZhv+1dmcY/o90OvWjubm/ebpkdr9zuXgWDc1z",
	"x4jrZRq4238wKyDgPqx0SEY7y28fN+Wgfb/MV77qVLGEjWLe+998GyeJyv+83FpfSiSo5VBPfIubxb8D",
	"AAD//+dMdffdLAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
