// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

// Defines values for ClusterCreateRequestClusterType.
const (
	Generic    ClusterCreateRequestClusterType = "generic"
	Hypershift ClusterCreateRequestClusterType = "hypershift"
	K3s        ClusterCreateRequestClusterType = "k3s"
	Microshift ClusterCreateRequestClusterType = "microshift"
	Openshift  ClusterCreateRequestClusterType = "openshift"
)

// Valid indicates whether the value is a known member of the ClusterCreateRequestClusterType enum.
func (e ClusterCreateRequestClusterType) Valid() bool {
	switch e {
	case Generic:
		return true
	case Hypershift:
		return true
	case K3s:
		return true
	case Microshift:
		return true
	case Openshift:
		return true
	default:
		return false
	}
}

// Defines values for ClusterCreateRequestServiceType.
const (
	Cluster ClusterCreateRequestServiceType = "cluster"
)

// Valid indicates whether the value is a known member of the ClusterCreateRequestServiceType enum.
func (e ClusterCreateRequestServiceType) Valid() bool {
	switch e {
	case Cluster:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Fail HealthStatus = "fail"
	Pass HealthStatus = "pass"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Fail:
		return true
	case Pass:
		return true
	default:
		return false
	}
}

// Defines values for VMCreateRequestServiceType.
const (
	Vm VMCreateRequestServiceType = "vm"
)

// Valid indicates whether the value is a known member of the VMCreateRequestServiceType enum.
func (e VMCreateRequestServiceType) Valid() bool {
	switch e {
	case Vm:
		return true
	default:
		return false
	}
}

// Access defines model for Access.
type Access struct {
	SshPublicKey *string `json:"ssh_public_key,omitempty"`
}

// ClusterCreateRequest defines model for ClusterCreateRequest.
type ClusterCreateRequest struct {
	ClusterType  ClusterCreateRequestClusterType `json:"cluster_type"`
	ControlPlane *struct {
		Count *int `json:"count,omitempty"`
	} `json:"control_plane,omitempty"`
	Metadata    ServiceMetadata                 `json:"metadata"`
	ServiceType ClusterCreateRequestServiceType `json:"service_type"`
	Workers     *struct {
		Count *int `json:"count,omitempty"`
	} `json:"workers,omitempty"`
}

// ClusterCreateRequestClusterType defines model for ClusterCreateRequest.ClusterType.
type ClusterCreateRequestClusterType string

// ClusterCreateRequestServiceType defines model for ClusterCreateRequest.ServiceType.
type ClusterCreateRequestServiceType string

// ClusterList defines model for ClusterList.
type ClusterList struct {
	NextPageToken *string            `json:"next_page_token,omitempty"`
	Results       *[]ClusterResource `json:"results,omitempty"`
}

// ClusterResource defines model for ClusterResource.
type ClusterResource struct {
	Id      *string `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
	Status  *string `json:"status,omitempty"`
	Version *string `json:"version,omitempty"`
}

// Error RFC 7807 compliant error response
type Error struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// GuestOS defines model for GuestOS.
type GuestOS struct {
	// Type kcli profile name
	Type string `json:"type"`
}

// Health defines model for Health.
type Health struct {
	Message *string       `json:"message,omitempty"`
	Status  *HealthStatus `json:"status,omitempty"`
	Uptime  *float32      `json:"uptime,omitempty"`
	Version *string       `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Memory defines model for Memory.
type Memory struct {
	// Size Memory size with unit suffix (MB, GB, TB)
	Size string `json:"size"`
}

// ServiceMetadata defines model for ServiceMetadata.
type ServiceMetadata struct {
	Name string `json:"name"`
}

// VMCreateRequest defines model for VMCreateRequest.
type VMCreateRequest struct {
	Access      *Access                    `json:"access,omitempty"`
	GuestOs     GuestOS                    `json:"guest_os"`
	Memory      Memory                     `json:"memory"`
	Metadata    ServiceMetadata            `json:"metadata"`
	ServiceType VMCreateRequestServiceType `json:"service_type"`
	Vcpu        *Vcpu                      `json:"vcpu,omitempty"`
}

// VMCreateRequestServiceType defines model for VMCreateRequest.ServiceType.
type VMCreateRequestServiceType string

// VMList defines model for VMList.
type VMList struct {
	NextPageToken *string       `json:"next_page_token,omitempty"`
	Results       *[]VMResource `json:"results,omitempty"`
}

// VMResource defines model for VMResource.
type VMResource struct {
	Id     *string `json:"id,omitempty"`
	Ip     *string `json:"ip,omitempty"`
	Name   *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
}

// Vcpu defines model for Vcpu.
type Vcpu struct {
	Count *int `json:"count,omitempty"`
}

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	MaxPageSize *int    `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
	PageToken   *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListVMsParams defines parameters for ListVMs.
type ListVMsParams struct {
	MaxPageSize *int    `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
	PageToken   *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = ClusterCreateRequest

// CreateVMJSONRequestBody defines body for CreateVM for application/json ContentType.
type CreateVMJSONRequestBody = VMCreateRequest
