// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
)

// Defines values for ClusterSpecServiceType.
const (
	ClusterSpecServiceTypeCluster ClusterSpecServiceType = "cluster"
)

// Valid indicates whether the value is a known member of the ClusterSpecServiceType enum.
func (e ClusterSpecServiceType) Valid() bool {
	switch e {
	case ClusterSpecServiceTypeCluster:
		return true
	default:
		return false
	}
}

// Defines values for ControlPlaneNodesCount.
const (
	N1 ControlPlaneNodesCount = 1
	N3 ControlPlaneNodesCount = 3
	N5 ControlPlaneNodesCount = 5
)

// Valid indicates whether the value is a known member of the ControlPlaneNodesCount enum.
func (e ControlPlaneNodesCount) Valid() bool {
	switch e {
	case N1:
		return true
	case N3:
		return true
	case N5:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Fail HealthStatus = "fail"
	Pass HealthStatus = "pass"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Fail:
		return true
	case Pass:
		return true
	default:
		return false
	}
}

// Defines values for VMSpecServiceType.
const (
	Vm VMSpecServiceType = "vm"
)

// Valid indicates whether the value is a known member of the VMSpecServiceType enum.
func (e VMSpecServiceType) Valid() bool {
	switch e {
	case Vm:
		return true
	default:
		return false
	}
}

// Access defines model for Access.
type Access struct {
	SshPublicKey *string `json:"ssh_public_key,omitempty"`
}

// Cluster Kubernetes cluster resource
type Cluster struct {
	Id *string `json:"id,omitempty"`

	// Path Resource path (e.g. clusters/{id})
	Path *string `json:"path,omitempty"`

	// Spec Provider-agnostic cluster specification aligned with the DCM catalog ClusterSpec
	Spec   ClusterSpec `json:"spec"`
	Status *string     `json:"status,omitempty"`
}

// ClusterList defines model for ClusterList.
type ClusterList struct {
	NextPageToken *string    `json:"next_page_token,omitempty"`
	Results       *[]Cluster `json:"results,omitempty"`
}

// ClusterSpec Provider-agnostic cluster specification aligned with the DCM catalog ClusterSpec
type ClusterSpec struct {
	Metadata *ServiceMetadata `json:"metadata,omitempty"`
	Nodes    *Nodes           `json:"nodes,omitempty"`

	// ProviderHints Provider-specific configuration (e.g. kcli profile overrides)
	ProviderHints *ProviderHints         `json:"provider_hints,omitempty"`
	ServiceType   ClusterSpecServiceType `json:"service_type"`

	// Version Kubernetes version (e.g. 1.30)
	Version              *string                `json:"version,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ClusterSpecServiceType defines model for ClusterSpec.ServiceType.
type ClusterSpecServiceType string

// ControlPlaneNodes defines model for ControlPlaneNodes.
type ControlPlaneNodes struct {
	Count *ControlPlaneNodesCount `json:"count,omitempty"`
}

// ControlPlaneNodesCount defines model for ControlPlaneNodes.Count.
type ControlPlaneNodesCount int

// Disk defines model for Disk.
type Disk struct {
	// Capacity Disk capacity with unit suffix (MB, GB, TB)
	Capacity string `json:"capacity"`
	Name     string `json:"name"`
}

// Error RFC 7807 compliant error response
type Error struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// GuestOS defines model for GuestOS.
type GuestOS struct {
	// Type OS identifier mapped to a kcli profile (e.g. fedora-39, rhel-9)
	Type string `json:"type"`
}

// Health defines model for Health.
type Health struct {
	Message *string       `json:"message,omitempty"`
	Status  *HealthStatus `json:"status,omitempty"`
	Uptime  *float32      `json:"uptime,omitempty"`
	Version *string       `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Memory defines model for Memory.
type Memory struct {
	// Size Memory size with unit suffix (MB, GB, TB)
	Size string `json:"size"`
}

// Nodes defines model for Nodes.
type Nodes struct {
	ControlPlane *ControlPlaneNodes `json:"control_plane,omitempty"`
	Workers      *WorkerNodes       `json:"workers,omitempty"`
}

// ProviderHints Provider-specific configuration (e.g. kcli profile overrides)
type ProviderHints map[string]interface{}

// ServiceMetadata defines model for ServiceMetadata.
type ServiceMetadata struct {
	Labels *map[string]string `json:"labels,omitempty"`
	Name   string             `json:"name"`
}

// Storage defines model for Storage.
type Storage struct {
	Disks *[]Disk `json:"disks,omitempty"`
}

// VM Virtual Machine resource
type VM struct {
	Id *string `json:"id,omitempty"`

	// Path Resource path (e.g. vms/{id})
	Path *string `json:"path,omitempty"`

	// Spec Provider-agnostic VM specification aligned with the DCM catalog VMSpec
	Spec   VMSpec  `json:"spec"`
	Status *string `json:"status,omitempty"`
}

// VMList defines model for VMList.
type VMList struct {
	NextPageToken *string `json:"next_page_token,omitempty"`
	Results       *[]VM   `json:"results,omitempty"`
}

// VMSpec Provider-agnostic VM specification aligned with the DCM catalog VMSpec
type VMSpec struct {
	Access   *Access          `json:"access,omitempty"`
	GuestOs  *GuestOS         `json:"guest_os,omitempty"`
	Memory   *Memory          `json:"memory,omitempty"`
	Metadata *ServiceMetadata `json:"metadata,omitempty"`

	// ProviderHints Provider-specific configuration (e.g. kcli profile overrides)
	ProviderHints        *ProviderHints         `json:"provider_hints,omitempty"`
	ServiceType          VMSpecServiceType      `json:"service_type"`
	Storage              *Storage               `json:"storage,omitempty"`
	Vcpu                 *Vcpu                  `json:"vcpu,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// VMSpecServiceType defines model for VMSpec.ServiceType.
type VMSpecServiceType string

// Vcpu defines model for Vcpu.
type Vcpu struct {
	Count *int `json:"count,omitempty"`
}

// WorkerNodes defines model for WorkerNodes.
type WorkerNodes struct {
	Count *int `json:"count,omitempty"`
}

// ListClustersParams defines parameters for ListClusters.
type ListClustersParams struct {
	MaxPageSize *int    `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
	PageToken   *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateClusterParams defines parameters for CreateCluster.
type CreateClusterParams struct {
	// Id Client-specified instance ID for idempotent creation (provided by SPM)
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// ListVMsParams defines parameters for ListVMs.
type ListVMsParams struct {
	MaxPageSize *int    `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`
	PageToken   *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateVMParams defines parameters for CreateVM.
type CreateVMParams struct {
	// Id Client-specified instance ID for idempotent creation (provided by SPM)
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = Cluster

// CreateVMJSONRequestBody defines body for CreateVM for application/json ContentType.
type CreateVMJSONRequestBody = VM

// Getter for additional properties for ClusterSpec. Returns the specified
// element and whether it was found
func (a ClusterSpec) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ClusterSpec
func (a *ClusterSpec) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ClusterSpec to handle AdditionalProperties
func (a *ClusterSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["nodes"]; found {
		err = json.Unmarshal(raw, &a.Nodes)
		if err != nil {
			return fmt.Errorf("error reading 'nodes': %w", err)
		}
		delete(object, "nodes")
	}

	if raw, found := object["provider_hints"]; found {
		err = json.Unmarshal(raw, &a.ProviderHints)
		if err != nil {
			return fmt.Errorf("error reading 'provider_hints': %w", err)
		}
		delete(object, "provider_hints")
	}

	if raw, found := object["service_type"]; found {
		err = json.Unmarshal(raw, &a.ServiceType)
		if err != nil {
			return fmt.Errorf("error reading 'service_type': %w", err)
		}
		delete(object, "service_type")
	}

	if raw, found := object["version"]; found {
		err = json.Unmarshal(raw, &a.Version)
		if err != nil {
			return fmt.Errorf("error reading 'version': %w", err)
		}
		delete(object, "version")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ClusterSpec to handle AdditionalProperties
func (a ClusterSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Metadata != nil {
		object["metadata"], err = json.Marshal(a.Metadata)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
		}
	}

	if a.Nodes != nil {
		object["nodes"], err = json.Marshal(a.Nodes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'nodes': %w", err)
		}
	}

	if a.ProviderHints != nil {
		object["provider_hints"], err = json.Marshal(a.ProviderHints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider_hints': %w", err)
		}
	}

	object["service_type"], err = json.Marshal(a.ServiceType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'service_type': %w", err)
	}

	if a.Version != nil {
		object["version"], err = json.Marshal(a.Version)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'version': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for VMSpec. Returns the specified
// element and whether it was found
func (a VMSpec) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for VMSpec
func (a *VMSpec) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for VMSpec to handle AdditionalProperties
func (a *VMSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access"]; found {
		err = json.Unmarshal(raw, &a.Access)
		if err != nil {
			return fmt.Errorf("error reading 'access': %w", err)
		}
		delete(object, "access")
	}

	if raw, found := object["guest_os"]; found {
		err = json.Unmarshal(raw, &a.GuestOs)
		if err != nil {
			return fmt.Errorf("error reading 'guest_os': %w", err)
		}
		delete(object, "guest_os")
	}

	if raw, found := object["memory"]; found {
		err = json.Unmarshal(raw, &a.Memory)
		if err != nil {
			return fmt.Errorf("error reading 'memory': %w", err)
		}
		delete(object, "memory")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["provider_hints"]; found {
		err = json.Unmarshal(raw, &a.ProviderHints)
		if err != nil {
			return fmt.Errorf("error reading 'provider_hints': %w", err)
		}
		delete(object, "provider_hints")
	}

	if raw, found := object["service_type"]; found {
		err = json.Unmarshal(raw, &a.ServiceType)
		if err != nil {
			return fmt.Errorf("error reading 'service_type': %w", err)
		}
		delete(object, "service_type")
	}

	if raw, found := object["storage"]; found {
		err = json.Unmarshal(raw, &a.Storage)
		if err != nil {
			return fmt.Errorf("error reading 'storage': %w", err)
		}
		delete(object, "storage")
	}

	if raw, found := object["vcpu"]; found {
		err = json.Unmarshal(raw, &a.Vcpu)
		if err != nil {
			return fmt.Errorf("error reading 'vcpu': %w", err)
		}
		delete(object, "vcpu")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for VMSpec to handle AdditionalProperties
func (a VMSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Access != nil {
		object["access"], err = json.Marshal(a.Access)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'access': %w", err)
		}
	}

	if a.GuestOs != nil {
		object["guest_os"], err = json.Marshal(a.GuestOs)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'guest_os': %w", err)
		}
	}

	if a.Memory != nil {
		object["memory"], err = json.Marshal(a.Memory)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'memory': %w", err)
		}
	}

	if a.Metadata != nil {
		object["metadata"], err = json.Marshal(a.Metadata)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
		}
	}

	if a.ProviderHints != nil {
		object["provider_hints"], err = json.Marshal(a.ProviderHints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider_hints': %w", err)
		}
	}

	object["service_type"], err = json.Marshal(a.ServiceType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'service_type': %w", err)
	}

	if a.Storage != nil {
		object["storage"], err = json.Marshal(a.Storage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'storage': %w", err)
		}
	}

	if a.Vcpu != nil {
		object["vcpu"], err = json.Marshal(a.Vcpu)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'vcpu': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
